import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { defaults, defaultPlan, rewards, forecast, spending, type Dataset } from '../src/engine.ts';
const data: Dataset = JSON.parse(await readFile('runtime-data/dataset.json', 'utf8'));
const s = { ...defaults(), date:'2026-10-06', jewels:75000, horseTickets:50, supportTickets:50, fragments:20, circle:'A+', team:'CLASS 5', champion:'【그레이드】 A결 3위', loh:'【플레티넘 3】', daily:true, dailyDate:'2025-08-08', pass:true, medal:true, monthlyHorse:4, monthlySupport:6 };
const period = rewards(data,s,'2026-10-02','2026-10-16',true);
assert.deepEqual(period.total,{jewels:11080,horseTickets:12,supportTickets:12,fragments:6});
const pickup = data.pickups.find(p=>p.start==='2026-10-16')!;
assert.ok(pickup);
for(const pulls of [200,400,600]) assert.equal(spending({...defaultPlan(),enabled:true,supportPulls:pulls},pickup),pulls*150);
assert.equal(spending({...defaultPlan(),enabled:true,supportTickets:20,freePulls:80},pickup),45000);
assert.throws(()=>spending({...defaultPlan(),enabled:true,supportTickets:500},pickup));
assert.throws(()=>spending({...defaultPlan(),enabled:true,freePulls:81},pickup));
const rows = forecast(data,{...s,date:'2026-10-06'}, {[pickup.id]:{...defaultPlan(),enabled:true,freePulls:80}});
const first = rows.find(r=>r.pickup.id===pickup.id)!;
assert.equal(first.cost,48000);
assert.equal(first.after.jewels,36400);
assert.equal(first.after.supportTickets,62);
const next = rows[rows.indexOf(first)+1]; assert.equal(next.before.jewels,first.after.jewels+next.income.jewels);
assert.equal(rewards(data,{...s,daily:false},'2026-10-02','2026-10-16',true).breakdown['데일리 쥬얼팩'].jewels,0);
assert.equal(rewards(data,{...s,pass:false},'2026-10-02','2026-10-16',true).breakdown['트레이닝 패스'].jewels,500);
const startExclusive = rewards(data,s,'2026-10-02','2026-10-02').total; assert.deepEqual(startExclusive,{jewels:0,horseTickets:0,supportTickets:0,fragments:0});
assert.throws(()=>rewards(data,s,'2026-10-02','2030-01-01'));
console.log('PASS: original period totals, original first pickup balance, 1/2/3 ceilings, tickets/free draws, continuous balances, purchases, date boundaries, coverage');
